<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/31
 * Time: 16:57
 */

namespace app\demo\model;


use think\Model;

class GoogleNews extends Model
{

    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}